apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: us-docker.pkg.dev/cloud-computing-428321/cloud-computing/service1
          volumeMounts:
            - mountPath: /app/storage
              name: shared-storage
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: service1-service
spec:
  type: LoadBalancer
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000